"""empty message

Revision ID: 161c1b8db779
Revises: 5aa2d1272ef6
Create Date: 2020-01-23 20:27:39.959439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161c1b8db779'
down_revision = '5aa2d1272ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('available_booking_times', sa.ARRAY(sa.DateTime()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'available_booking_times')
    # ### end Alembic commands ###
