"""empty message

Revision ID: 5d7c99e1c353
Revises: 4d2b6fa4e6c9
Create Date: 2020-01-17 18:02:18.330903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d7c99e1c353'
down_revision = '4d2b6fa4e6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'datetime', new_column_name='start_time')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'start_time', new_column_name='datetime')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
