"""empty message

Revision ID: 6c0ced653ff8
Revises: 96ba4a17b5af
Create Date: 2020-01-16 20:12:06.408663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0ced653ff8'
down_revision = '96ba4a17b5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('sticky_message', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('sticky_title', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('sticky_message', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('sticky_title', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'sticky_title')
    op.drop_column('Venue', 'sticky_message')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'sticky_title')
    op.drop_column('Artist', 'sticky_message')
    op.drop_table('Show')
    # ### end Alembic commands ###
