"""empty message

Revision ID: f70ba6783227
Revises: 161c1b8db779
Create Date: 2020-01-23 21:42:18.587203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f70ba6783227'
down_revision = '161c1b8db779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'available_booking_times',
               existing_type=postgresql.ARRAY(postgresql.TIMESTAMP()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'available_booking_times',
               existing_type=postgresql.ARRAY(postgresql.TIMESTAMP()),
               nullable=True)
    # ### end Alembic commands ###
